/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JayJomJohn
 */
public class Main extends javax.swing.JFrame {
    String path = null;
    byte[] person_image = null;
 
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public Main() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        
        showIcon();
        showtable();
        showRandomAccount();
        showJListcombo();
    }
    
public final void showtable(){
    try {
        String query = "SELECT ID,FIRSTNAME,LASTNAME,MIDDLENAME,GENDER,DATEOFBIRTH,AGE,ADDRESS FROM crud";
        pst=conn.prepareStatement(query);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
    }
}

public void showRandomAccount(){
    Random ra = new Random();
    txt_id.setText(""+ra.nextInt(10000+1));
}

private void showIcon() {
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("batman.png")));
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        label_photo.setIcon(i);
        person_image = null;
    }

public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_middlename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1_male = new javax.swing.JRadioButton();
        jRadioButton2_female = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        label_photo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 650));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(18);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 377, 890, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, 30));

        txt_age.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, 30));

        txt_firstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, 30));

        txt_lastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Address:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 120, 30));

        txt_middlename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Middle Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, 30));

        jRadioButton1_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1_male);
        jRadioButton1_male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1_male.setText("Male");
        jRadioButton1_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jRadioButton1_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 80, 30));

        jRadioButton2_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2_female);
        jRadioButton2_female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2_female.setText("Female");
        jRadioButton2_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jRadioButton2_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 180, 90, 30));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Browse");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 170, 60));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CREATE");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 180, 60));

        jPanel5.setBackground(new java.awt.Color(0, 102, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 180, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 1200, 10));

        jPanel6.setBackground(new java.awt.Color(153, 51, 0));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 180, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 30));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Date of Birth:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Age:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 30));

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane2.setViewportView(txt_address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 300, -1));

        label_photo.setBackground(new java.awt.Color(0, 0, 0));
        label_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_photo.setOpaque(true);
        jPanel1.add(label_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 220, 220));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CLEAR");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 180, 60));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 150, 30));

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jList1.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 290, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showOpenDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             try {
                 File selectedFile = fileChooser.getSelectedFile();
                 String path = selectedFile.getAbsolutePath();
                 label_photo.setIcon(ResizeImage(path));
                 
                 File image = new File(path);
                 FileInputStream fis = new FileInputStream(image);
                 ByteArrayOutputStream bos= new ByteArrayOutputStream();
                 byte[] buf = new byte[1024];
                 for(int readNum; (readNum=fis.read(buf))!= -1; ){
                     bos.write(buf,0,readNum);
                 }
                 person_image=bos.toByteArray();
                 
             }catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
             }
              
        }else if(result == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(this, "No File Selected!", "ATTENTION", JOptionPane.ERROR_MESSAGE);             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
    int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","AddRecord",JOptionPane.YES_NO_OPTION);
    if(x==0){ 
            
              
        if(txt_firstname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Firstname cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_firstname.requestFocus();
            
        } else if(txt_lastname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Lastname cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_lastname.requestFocus();
                        
        } else if(txt_middlename.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Middlename cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_middlename.requestFocus();           
            
        } else if(jRadioButton1_male.isSelected() == false && jRadioButton2_female.isSelected() == false){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Gender cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            
        } else if(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You must select date a valid type to proceed!", "WARNING!", JOptionPane.WARNING_MESSAGE); 
            jDateChooser1.requestFocus();
            
        } else if(txt_age.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Age cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_age.requestFocus();           
            
        } else if(txt_address.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Address cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_address.requestFocus();                       
            
        } else if(person_image != null) {    
            
            
            
        try {
            String query = "INSERT INTO crud(id,firstname,lastname,middlename,gender,dateofbirth,age,address,photo)"
                    + "VALUES(?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);
            pst.setString(1,txt_id.getText());
            pst.setString(2,txt_firstname.getText().toUpperCase());
            pst.setString(3,txt_lastname.getText().toUpperCase());
            pst.setString(4,txt_middlename.getText().toUpperCase());
            jRadioButton1_male.setActionCommand("Male");
            jRadioButton2_female.setActionCommand("Female");
            pst.setString(5,buttonGroup1.getSelection().getActionCommand());
            pst.setString(6,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(7,txt_age.getText());
            pst.setString(8,txt_address.getText().toUpperCase());
            pst.setBytes(9,person_image);
            pst.execute();
            
            
            JOptionPane.showMessageDialog(rootPane,"Create Success!");
            showtable();
            showJListcombo();
        
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
        }
        
        
        //VALIDATION IMAGE
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"You Cannot Save Data Without A Person Image","ERROR",JOptionPane.ERROR_MESSAGE,null);
             
            }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){   
            evt.consume();
            getToolkit().beep();
        } 
        if(txt_age.getText().length() >= 2) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_ageKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      clearfields();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        try{
            int row = jTable1.getSelectedRow();
            String Table_click=(jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM crud WHERE id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
   
             txt_id.setText(rs.getString("id"));
             txt_firstname.setText(rs.getString("firstname"));
             txt_lastname.setText(rs.getString("lastname"));
             txt_middlename.setText(rs.getString("middlename"));
             
             String gen = rs.getString("gender");
             if("Male".equals(gen)){
                 jRadioButton1_male.setSelected(true);
             }else if("Female".equals(gen)){
                 jRadioButton2_female.setSelected(true);
             }
             
             ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(rs.getString("dateofbirth"));  
             txt_age.setText(rs.getString("age"));
             txt_address.setText(rs.getString("address"));            
             
	  byte[] img = rs.getBytes("photo");
          ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH));
          label_photo.setIcon(imageIcon);

            

          }           
        }catch(Exception e) {          
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if(!jTable1.getSelectionModel().isSelectionEmpty()){
    
    int p = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete?","DELETE",JOptionPane.YES_NO_OPTION);
    if(p==0){
      
       
        try{
            int row =jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            String sql ="DELETE FROM crud WHERE id="+value;
            pst=conn.prepareStatement(sql);         
            pst.executeUpdate();
            showtable();
            JOptionPane.showMessageDialog(null,"Entry Successfully Deleted","Deleted", 3);
            
            
            }catch(SQLException e){
                   JOptionPane.showMessageDialog(this, e);   
        }        
        } 
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
         try{
            String list = (String)jList1.getSelectedValue();
            String sql = "SELECT * FROM crud WHERE address=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,list);
            rs=pst.executeQuery();
            if(rs.next()) {
   
             txt_id.setText(rs.getString("id"));
             txt_firstname.setText(rs.getString("firstname"));
             txt_lastname.setText(rs.getString("lastname"));
             txt_middlename.setText(rs.getString("middlename"));
             
             String gen = rs.getString("gender");
             if("Male".equals(gen)){
                 jRadioButton1_male.setSelected(true);
             }else if("Female".equals(gen)){
                 jRadioButton2_female.setSelected(true);
             }
             
             ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(rs.getString("dateofbirth"));  
             txt_age.setText(rs.getString("age"));
             txt_address.setText(rs.getString("address"));            
             
	  byte[] img = rs.getBytes("photo");
          ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH));
          label_photo.setIcon(imageIcon);

            

          }           
        }catch(Exception e) {          
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","System message!",JOptionPane.OK_OPTION); 
    if (x == 0) {  
        
         if(txt_firstname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Firstname cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_firstname.requestFocus();
            
        } else if(txt_lastname.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Lastname cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_lastname.requestFocus();
                        
        } else if(txt_middlename.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Middlename cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_middlename.requestFocus();           
            
        } else if(jRadioButton1_male.isSelected() == false && jRadioButton2_female.isSelected() == false){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Gender cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            
        } else if(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You must select date a valid type to proceed!", "WARNING!", JOptionPane.WARNING_MESSAGE); 
            jDateChooser1.requestFocus();
            
        } else if(txt_age.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Age cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_age.requestFocus();           
            
        } else if(txt_address.getText().isEmpty()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Address cannot be empty","Warning!",JOptionPane.WARNING_MESSAGE);    
            txt_address.requestFocus();                       
            
        } else if(person_image != null) {    
            
            
            
        try {
            String idnum = txt_id.getText();
            String query = "UPDATE crud SET firstname=?,"
                    + "lastname=?, middlename=?,"
                    + "gender=?,dateofbirth=?,age=?,"
                    + "address=?,photo=? WHERE id='"+idnum+"'";
            pst=conn.prepareStatement(query);
            pst.setString(1,txt_firstname.getText().toUpperCase());
            pst.setString(2,txt_lastname.getText().toUpperCase());
            pst.setString(3,txt_middlename.getText().toUpperCase());
            jRadioButton1_male.setActionCommand("Male");
            jRadioButton2_female.setActionCommand("Female");
            pst.setString(4,buttonGroup1.getSelection().getActionCommand());
            pst.setString(5,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(6,txt_age.getText());
            pst.setString(7,txt_address.getText().toUpperCase());
            pst.setBytes(8,person_image);
            pst.executeUpdate();            
            JOptionPane.showMessageDialog(rootPane,"Update Success!");
            showtable();
            showJListcombo();
        
            
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
        }
        
        
        //VALIDATION IMAGE
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"You Cannot Update Data Without A Person Image","ERROR",JOptionPane.ERROR_MESSAGE,null);
             
            }
  
    }
    }//GEN-LAST:event_jButton3ActionPerformed

public void showJListcombo(){
    DefaultListModel DLM = new DefaultListModel();
    try {
        String sql = "SELECT * FROM crud ";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String add = rs.getString("address");
            DLM.addElement(add);
        }
        jList1.setModel(DLM);
        
    } catch (Exception e) {
    }
}
  
    
void clearfields(){
    txt_firstname.setText("");
    txt_lastname.setText("");
    txt_middlename.setText("");
    buttonGroup1.clearSelection();
    jDateChooser1.setDate(null);
    txt_age.setText("");
    txt_address.setText("");
    showIcon();
    showRandomAccount();
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1_male;
    private javax.swing.JRadioButton jRadioButton2_female;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel label_photo;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_middlename;
    // End of variables declaration//GEN-END:variables
}
